##
# File: Makefile
# Project "mmlic"
# (c) 2011 SMSRelay AG
# Create: Andreas Fink (afink@smsrelay.com)
#
#	

all:
	-xcodebuild -target mmlic -configuration Release build
	-xcodebuild -target mminfo -configuration Release build
	-cp build/Release/mmlic ./mmlic
	-cp build/Release/mminfo ./mminfo

install:
	-xcodebuild -target mmlic -configuration Release build
	-xcodebuild -target mminfo -configuration Release build
	-cp build/Release/mmlic	/usr/bin/mmlic
	-cp build/Release/mminfo /usr/bin/mminfo

clean:
	-xcodebuild -target mmlic -configuration Release clean
	-xcodebuild -target mminfo -configuration Release clean

